In [7]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [8]:
#NOMINAL OR OHE Encoding
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [9]:
df=pd.DataFrame({
'color':['red','blue','green','green','red','blue']
})

In [10]:
df.head()

,color
0,red
1,blue
2,green
3,green
4,red


In [13]:
#create an instance of onehot encoder
encoder=OneHotEncoder()

In [15]:
encoded=encoder.fit_transform(df[['color']]).toarray()

In [16]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [17]:
encoder_df

,color_blue,color_green,color_red
0,0.0,0.0,1.0
1,1.0,0.0,0.0
2,0.0,1.0,0.0
3,0.0,1.0,0.0
4,0.0,0.0,1.0
5,1.0,0.0,0.0


In [18]:
encoder.transform([['blue']]).toarray()

C:\Users\Kirat\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [19]:
sns.load_dataset('tips')

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4
...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3
240,27.18,2.00,Female,Yes,Sat,Dinner,2
241,22.67,2.00,Male,Yes,Sat,Dinner,2
242,17.82,1.75,Male,No,Sat,Dinner,2


In [20]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()


In [22]:
lbl_encoder.fit_transform(df[['color']])

C:\Users\Kirat\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 0, 1, 1, 2, 0])

In [23]:
lbl_encoder.transform([['blue']])

C:\Users\Kirat\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([0])

In [ ]:
#labe used to assign the ranks

In [24]:
#ordinal Encoding
# encoded the categorical data
from sklearn.preprocessing import OrdinalEncoder




In [25]:
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [26]:
df

,size
0,small
1,medium
2,large
3,medium
4,small
5,large


In [ ]:
## create an instance of OrdinalEncoder and tehn fit_transform

In [27]:
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [29]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [30]:
encoder.transform([['small']])

C:\Users\Kirat\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])

In [32]:
#target guided ordinal encoding technique
df=pd.DataFrame({
    'city':['New York','London','Paris','Tokyo','New York','paris'],
    'price':[200,150,300,250,180,320]
})

In [33]:
df.head()

,city,price
0,New York,200
1,London,150
2,Paris,300
3,Tokyo,250
4,New York,180


In [35]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [36]:
mean_price

{'London': 150.0,
 'New York': 190.0,
 'Paris': 300.0,
 'Tokyo': 250.0,
 'paris': 320.0}

In [37]:
df['city_encoded']=df['city'].map(mean_price)

In [39]:
df[['city','city_encoded']]

,city,city_encoded
0,New York,190.0
1,London,150.0
2,Paris,300.0
3,Tokyo,250.0
4,New York,190.0
5,paris,320.0


In [42]:
df2=sns.load_dataset('tips')

In [43]:
mean_price1=df2.groupby('time')['total_bill'].mean().to_dict()

C:\Users\Kirat\AppData\Local\Temp\ipykernel_2420\2242118604.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_price1=df2.groupby('time')['total_bill'].mean().to_dict()


In [48]:
print(df.columns)  # Step 1

df.columns = df.columns.str.strip()  # Step 2 (clean spaces)

mean_total_bill = df.groupby('time')['total_bill'].mean()  # Step 3

print(mean_total_bill)  # Step 4

Index(['city', 'price', 'city_encoded'], dtype='object')


KeyError: 'time'